### PR TITLE
Optional precompile mode

### PR DESCRIPTION
**Pull request by diclophis**

### CODE REVIEW

**Comment by cantino** [comment]
Is this because we're so far behind jasmine HEAD?

**Comment by diclophis** [comment]
We need to disable the activation of the asset pipeline because if we are building parallel on a local workstation the asset compilation processes will clobber each others output... It needs to be disabled when its "CI" or "LOCAL-CI-PARALELL" but enabled when its in "DEV-TEST" mode, so you can reload the browser to see the updated JS.

**Comment by cantino** [comment]
I didn't know we built in parallel?

**Comment by diclophis** [comment]
Its a WIP update to the `/usr/bin/devops` command toolkit that would allow people to run the test suite in an local "circleci like environment" including customizable worker count parallelization options

**Comment by diclophis** [comment]
@bgreg related: https://github.com/mavenlink/mavenlink/pull/4766

**Pull request merged**
